Refactor LcPtr, DetachablePtr for readability
aws/aws-lc-rs pull request #211
Opened 2023-08-03 21:58 UTC by skmcgrail

### Description of changes: 
Just cleans up the usage so they you don't need to specify `LcPtr<*mut T>` or `DetachableLcPtr<*mut T>` but can just say `LcPtr<T>` or `DetacableLcPtr<T>` similar to how `ConstPtr<T>` is already how that type functions.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the ISC license.

2023-08-09 11:46 UTC, justsmth requested changes

2023-08-09 11:46 UTC, justsmth commented on aws-lc-rs/src/ptr.rs
> +impl<P: Pointer + Copy> ManagedPointer<P> {
Why do we need `P` to be `Copy`? This might be an artifact of some method we wrote that has since been removed.(?)

2023-08-09 11:46 UTC, justsmth commented on aws-lc-rs/src/ptr.rs
>      pub fn as_const<T>(&self) -> ConstPointer<T> {
This has been bothering me -- `T` should be an associated type for the Pointer instead of a generic for this function.

2023-08-14 17:35 UTC, samuel40791765 approved these changes

2023-08-14 17:47 UTC, merged